#!/bin/bash

#protodir=$(pkg-config --variable=xcbincludedir xcb-proto)
protodir=$(realpath xml)

protos="xproto"

mkdir -p output
for p in $protos ; do
    ( cd output && ../c_client.py --server-side -s '3x' -c 'foo_center_footer' -l 'foo_left_footer' $protodir/$p.xml )
done
